language: go

go:
  - 1.9.x
  - 1.x

script:
  - go test -v -covermode=count -coverprofile=coverage.out
    $HOME/gopath/bin/goveralls -coverprofile=coverage.out -service=https://travis-ci.org/Abdujabbor/electrician -repotoken op2HIxJuopKOF4CT3zvDDWw7ysQcPlxuM
  - go test -v -race ./...