language: go
go:
- 1.9.x
- 1.x
script:
  - go test -v -covermode=count -coverprofile=coverage.out ./...
  - goveralls -coverprofile=coverage.out -service travis-ci -repotoken op2HIxJuopKOF4CT3zvDDWw7ysQcPlxuM